services:
  wordlebot:
    image: wordle
    environment:
      - TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
      - TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
      - TWILIO_FROM_NUMBER=$TWILIO_FROM_NUMBER
      - PRODUCTION=$PRODUCTION
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    volumes:
      - "./data:/app/data"
